2017-10-18 09:54:19 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at protobuf.clazz.s2s.BackpackProto$Backpack$Builder.setPrizeDesc(BackpackProto.java:5515)
	at com.cai.constant.item.ItemOffLineMatch.getItemDetail(ItemOffLineMatch.java:83)
	at com.cai.constant.item.ItemOffLineMatch.use(ItemOffLineMatch.java:95)
	at com.cai.service.ItemService.use(ItemService.java:208)
	at com.cai.handler.c2s.ItemHandler.useItem(ItemHandler.java:81)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:41)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 16:21:19 [ERROR]-[com.cai.common.util.NamedThreadFactory] 线程【global-thread-1】抛出异常。
java.lang.NoSuchMethodError: com.cai.dao.ClubDao.getSignSeq()I
	at com.cai.service.ItemService.immeUseItem(ItemService.java:140)
	at com.cai.handler.c2s.ItemHandler.immeUseItem(ItemHandler.java:132)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:48)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 16:55:15 [ERROR]-[com.cai.redis.listener.TopicAllMessageDelegate] error
java.lang.NullPointerException
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:309)
	at protobuf.redis.ProtoRedis$RsAccountResponse.<init>(ProtoRedis.java:15416)
	at protobuf.redis.ProtoRedis$RsAccountResponse.<init>(ProtoRedis.java:15317)
	at protobuf.redis.ProtoRedis$RsAccountResponse$1.parsePartialFrom(ProtoRedis.java:15508)
	at protobuf.redis.ProtoRedis$RsAccountResponse$1.parsePartialFrom(ProtoRedis.java:1)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:309)
	at protobuf.redis.ProtoRedis$RedisResponse.<init>(ProtoRedis.java:27158)
	at protobuf.redis.ProtoRedis$RedisResponse.<init>(ProtoRedis.java:27119)
	at protobuf.redis.ProtoRedis$RedisResponse$1.parsePartialFrom(ProtoRedis.java:27274)
	at protobuf.redis.ProtoRedis$RedisResponse$1.parsePartialFrom(ProtoRedis.java:1)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:141)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:188)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:193)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at protobuf.redis.ProtoRedis$RedisResponse.parseFrom(ProtoRedis.java:27760)
	at com.cai.redis.listener.TopicAllMessageDelegate.handleMessage(TopicAllMessageDelegate.java:47)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.listener.adapter.MessageListenerAdapter$MethodInvoker.invoke(MessageListenerAdapter.java:145)
	at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:374)
	at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:310)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:249)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:239)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$1.run(RedisMessageListenerContainer.java:967)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 17:12:12 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:12:16 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:12:33 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:12:37 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:13:07 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:13:09 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:14:42 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:197)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:242)
	at com.cai.dao.CoreDao.queryForObject(CoreDao.java:18)
	at com.cai.dao.ClubDao.getMatchSignUp(ClubDao.java:341)
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:254)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sql/club.xml.  
--- The error occurred while applying a parameter map.  
--- Check the getMatchSignUp-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:244)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:194)
	... 13 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_d' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 19 more
2017-10-18 17:17:17 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 17:17:38 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 18:19:37 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 18:30:07 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 18:30:11 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:154)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:52)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-10-18 18:35:17 [ERROR]-[com.xianyi.framework.handler.ReqExecutor] ##########!处理消息错误,玩家:null,请求类型:11,e:{}
java.lang.NullPointerException
	at com.cai.service.ItemService.getUseItemsLogDetail(ItemService.java:260)
	at com.cai.handler.c2s.ItemHandler.getUseItemsLogDetail(ItemHandler.java:162)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:55)
	at com.cai.handler.c2s.ItemHandler.execute(ItemHandler.java:1)
	at com.xianyi.framework.handler.IClientHandler.doExecute(IClientHandler.java:41)
	at com.xianyi.framework.handler.ReqExecutor.run(ReqExecutor.java:66)
	at com.cai.common.util.GlobalExecutor.lambda$0(GlobalExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
